---
name: CI-check

on:
  push:
    branches-ignore:
      - master

  pull_request:

  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Lint Code Base
        uses: super-linter/super-linter/slim@2da136927bd4a73596db63044b504547c62cb854
        env:
          VALIDATE_ALL_CODEBASE: true
          ENABLE_GITHUB_PULL_REQUEST_SUMMARY_COMMENT: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
