---
name: CI-check

on:
  push:
    branches-ignore:
      - master

  pull_request:

  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Lint Code Base
        uses: super-linter/super-linter/slim@4ce20838b8ab83717e78138c5b3a1407148e0918
        env:
          VALIDATE_ALL_CODEBASE: true
          ENABLE_GITHUB_PULL_REQUEST_SUMMARY_COMMENT: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
